[project]
name = "final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "py7zr>=1.0.0",
    "tqdm>=4.67.1",
]

[[index]]
url = "https://mirrors.cernet.edu.cn/pypi/web/simple"
default = true
